### ISSUE TITLE
クソデカ小数を入れると検閲をすり抜けられる＆小数文字列のBigInt変換にエラー

### ISSUE THREAD

**Issue by nikachu2012** [sirokuma2020/common-divisor-multipcalculator#5]
### クソデカ小数を入れると検閲をすり抜けられる

<img width="420" alt="image" src="https://github.com/sirokuma2020/common-divisor-multipcalculator/assets/75615396/6a0a386c-67ce-4675-b9c2-36ba32ddb5fd">

多分JavaScriptの限界で丸められている

## 小数文字列のBigInt変換のエラー

Stacktrace: 
```
main.js:91 Uncaught SyntaxError: Cannot convert 9007199254740992.1 to a BigInt (at main.js:91:13)
    at BigInt (<anonymous>)
    at main.js:91:13
    at Array.forEach (<anonymous>)
    at Buuton (main.js:90:17)
    at HTMLButtonElement.onclick (（インデックス）:41:41)
```

<img width="598" alt="image" src="https://github.com/sirokuma2020/common-divisor-multipcalculator/assets/75615396/fc9ecdfa-99bd-4958-84ec-4e89459cbb16">
問題はここなはず

<img width="354" alt="image" src="https://github.com/sirokuma2020/common-divisor-multipcalculator/assets/75615396/ce6dadd3-7b12-4885-a8e0-e729f5817f69">
Number型に型変換してからの方がいいと思う

**Comment by sirokuma2020** [comment]
number型にしたら2^53までしか対応できないからどうにかする
